# Etapa base
FROM node:20-alpine

# Instala as dependências necessárias para compilar módulos nativos
RUN apk add --no-cache python3 make g++

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta
EXPOSE 3000

# Comando padrão
CMD ["npx", "nodemon", "server.js"]
